// To save on processing, just hardcode unique data.
// If raw data is dynamic, need to process on the fly.
export const uniqueYears = [
    2024,
    2023,
    2022,
    2021,
    2020,
    2019,
    2018,
    2017
];

export const uniqueRegions = [
    'CAR',
    'NCR',
    'Region I',
    'Region II',
    'Region III',
    'Region IV-A',
    'Region IV-B',
    'Region V',
    'Region VI',
    'Region VII',
    'Region VIII',
    'Region IX',
    'Region X',
    'Region XI',
    'Region XII',
    'Region XIII'
]

export const uniqueDistricts = [
    'Abra DEO',
    'Agusan del Norte DEO',
    'Agusan del Sur 1st DEO',
    'Agusan del Sur 2nd DEO',
    'Aklan DEO',
    'Albay 1st DEO',
    'Albay 2nd DEO',
    'Albay 3rd DEO',
    'Antique DEO',
    'Apayao 1st DEO',
    'Apayao 2nd DEO',
    'Aurora DEO',
    'Bacolod City DEO',
    'Baguio City DEO',
    'Bataan 1st DEO',
    'Bataan 2nd DEO',
    'Batanes DEO',
    'Batangas 1st DEO',
    'Batangas 2nd DEO',
    'Batangas 3rd DEO',
    'Batangas 4th DEO',
    'Benguet 1st DEO',
    'Benguet 2nd DEO',
    'Biliran DEO',
    'Bohol 1st DEO',
    'Bohol 2nd DEO',
    'Bohol 3rd DEO',
    'Bukidnon 1st DEO',
    'Bukidnon 2nd DEO',
    'Bukidnon 3rd DEO',
    'Bulacan 1st DEO',
    'Bulacan 2nd DEO',
    'Butuan City DEO',
    'Cagayan 1st DEO',
    'Cagayan 2nd DEO',
    'Cagayan 3rd DEO',
    'Cagayan de Oro City 1st DEO',
    'Cagayan de Oro City 2nd DEO',
    'Camarines Norte DEO',
    'Camarines Sur 1st DEO',
    'Camarines Sur 2nd DEO',
    'Camarines Sur 3rd DEO',
    'Camarines Sur 4th DEO',
    'Camarines Sur 5th DEO',
    'Camiguin DEO',
    'Capiz 1st DEO',
    'Capiz 2nd DEO',
    'CAR',
    'Catanduanes DEO',
    'Cavite 1st DEO',
    'Cavite 2nd DEO',
    'Cavite 3rd DEO',
    'Cebu 1st DEO',
    'Cebu 2nd DEO',
    'Cebu 3rd DEO',
    'Cebu 4th DEO',
    'Cebu 5th DEO',
    'Cebu 6th DEO',
    'Cebu 7th DEO',
    'Cebu City DEO',
    'Cotabato 1st DEO',
    'Cotabato 2nd DEO',
    'Cotabato 3rd DEO',
    'Davao City 2nd DEO',
    'Davao City DEO',
    'Davao de Oro 1st DEO',
    'Davao de Oro 2nd DEO',
    'Davao del Norte DEO',
    'Davao del Sur DEO',
    'Davao Occidental DEO',
    'Davao Oriental 1st DEO',
    'Davao Oriental 2nd DEO',
    'Dinagat Islands DEO',
    'Eastern Samar DEO',
    'Guimaras DEO',
    'Ifugao 2nd DEO',
    'Iligan City DEO',
    'Ilocos Norte 1st DEO',
    'Ilocos Norte 2nd DEO',
    'Ilocos Sur 1st DEO',
    'Ilocos Sur 2nd DEO',
    'Iloilo 1st DEO',
    'Iloilo 2nd DEO',
    'Iloilo 3rd DEO',
    'Iloilo 4th DEO',
    'Iloilo City DEO',
    'Isabela 1st DEO',
    'Isabela 2nd DEO',
    'Isabela 3rd DEO',
    'Isabela 4th DEO',
    'Isabela City DEO',
    'La Union 1st DEO',
    'La Union 2nd DEO',
    'Laguna 1st DEO',
    'Laguna 2nd DEO',
    'Laguna 3rd DEO',
    'Lanao del Norte 1st DEO',
    'Lanao del Norte 2nd DEO',
    'Las Piñas-Muntinlupa DEO',
    'Leyte 1st DEO',
    'Leyte 2nd DEO',
    'Leyte 3rd DEO',
    'Leyte 4th DEO',
    'Leyte 5th DEO',
    'Lower Kalinga DEO',
    'Malabon-Navotas DEO',
    'Marinduque DEO',
    'Masbate 1st DEO',
    'Masbate 2nd DEO',
    'Masbate 3rd DEO',
    'Metro Manila 1st DEO',
    'Metro Manila 2nd DEO',
    'Metro Manila 3rd DEO',
    'Mindoro Occidental DEO',
    'Mindoro Oriental DEO',
    'Misamis Occidental 1st DEO',
    'Misamis Occidental 2nd DEO',
    'Misamis Oriental 1st DEO',
    'Misamis Oriental 2nd DEO',
    'Mountain Province 1st DEO',
    'Mountain Province 2nd DEO',
    'NCR',
    'Negros Occidental 1st DEO',
    'Negros Occidental 2nd DEO',
    'Negros Occidental 3rd DEO',
    'Negros Occidental 4th DEO',
    'Negros Oriental 1st DEO',
    'Negros Oriental 2nd DEO',
    'Negros Oriental 3rd DEO',
    'North Manila DEO',
    'Northern Samar 1st DEO',
    'Northern Samar 2nd DEO',
    'Nueva Ecija 1st DEO',
    'Nueva Ecija 2nd DEO',
    'Nueva Vizcaya 2nd DEO',
    'Nueva Vizcaya DEO',
    'Palawan 1st DEO',
    'Palawan 2nd DEO',
    'Palawan 3rd DEO',
    'Pampanga 1st DEO',
    'Pampanga 2nd DEO',
    'Pampanga 3rd DEO',
    'Pangasinan 1st DEO',
    'Pangasinan 2nd DEO',
    'Pangasinan 3rd DEO',
    'Pangasinan 4th DEO',
    'Quezon 1st DEO',
    'Quezon 2nd DEO',
    'Quezon 3rd DEO',
    'Quezon 4th DEO',
    'Quezon City 1st DEO',
    'Quezon City 2nd DEO',
    'Quirino DEO',
    'Region I',
    'Region II',
    'Region III',
    'Region IV-A',
    'Region IV-B',
    'Region IX',
    'Region V',
    'Region VI',
    'Region VII',
    'Region VIII',
    'Region X',
    'Region XI',
    'Region XII',
    'Region XIII',
    'Rizal 1st DEO',
    'Rizal 2nd DEO',
    'Romblon DEO',
    'Samar 1st DEO',
    'Samar 2nd DEO',
    'Sarangani DEO',
    'Sorsogon 2nd DEO',
    'Sorsogon DEO',
    'South Cotabato 1st DEO',
    'South Cotabato 2nd DEO',
    'South Manila DEO',
    'Southern Leyte 1st DEO',
    'Southern Mindoro DEO',
    'Sultan Kudarat 1st DEO',
    'Sultan Kudarat 2nd DEO',
    'Surigao del Norte 1st DEO',
    'Surigao del Norte 2nd DEO',
    'Surigao del Sur 1st DEO',
    'Surigao del Sur 2nd DEO',
    'Tacloban City DEO',
    'Tarlac 2nd DEO',
    'Tarlac DEO',
    'Upper Kalinga DEO',
    'Zambales 1st DEO',
    'Zambales 2nd DEO',
    'Zamboanga City 2nd DEO',
    'Zamboanga del Norte 1st DEO',
    'Zamboanga del Norte 2nd DEO',
    'Zamboanga del Norte 3rd DEO',
    'Zamboanga del Norte 4th DEO',
    'Zamboanga del Sur 1st DEO',
    'Zamboanga del Sur 2nd DEO',
    'Zamboanga Sibugay 1st DEO',
    'Zamboanga Sibugay 2nd DEO'    
]