name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Debug folders
        run: cd /home/runner/work/floodcontrol/floodcontrol/WebAnalyzer/flood-analyzer
        
      - name: Debug folders2
        run: ls    

      - name: Install dependencies        
        uses: bahmutov/npm-install@v1
        with:
          working-directory: /home/runner/work/floodcontrol/floodcontrol/WebAnalyzer/flood-analyzer

      - name: Build project        
        run: npm run build
        working-directory: /home/runner/work/floodcontrol/floodcontrol/WebAnalyzer/flood-analyzer

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: /home/runner/work/floodcontrol/floodcontrol/WebAnalyzer/flood-analyzer/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: /home/runner/work/floodcontrol/floodcontrol/WebAnalyzer/flood-analyzer/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/floodcontrol/floodcontrol/WebAnalyzer/flood-analyzer/dist
          
      - name: After Deploy check dir
        run: ls /home/runner/work/floodcontrol/floodcontrol/WebAnalyzer/flood-analyzer/dist